name=input("Enter your name: ")
marks = int(input("Enter your marks score: "))
phone_number = int(input("Enter your phone number: "))
lines = "The name of the student is {}, his marks are {} and phone number is {}".format(name , marks, phone_number)
print(lines)